config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers,only: [:show,:edit,:update]
  get '/customers/:id/leave' => "customers#leave"
  patch '/customers/:id/hide' => "customers#hide"
  resources :cart_items,only: [:index,:create,:destroy,:update]
  delete '/cart_items' => "cart_items#reset"
  get '/products/:genre_id/search' => "products#search"
  resources :products,only: [:index,:show]
  resources :shippings,only: [:new,:create,:edit,:update,:destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/complete' => "orders#complete"
  post '/orders/complete' => "orders#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders,only: [:new,:create,:index,:show]
  root to: 'home#top'
  namespace :admin do
  	get '/' => "home#top"
  	devise_for :administrators
  	resources :products,only: [:index,:new,:create,:show,:edit,:update]
  	resources :genres,only: [:index,:create,:edit,:update]
  	resources :customers,only: [:index,:show,:edit,:update]
  	resources :orders,only: [:index,:show,:update]
  	resources :order_details,only: [:update]
  end

  get 'admin/search' => "admin/search#search"
  get '/search' => "search#search"

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	before_action :authenticate_admin_administrator!
  layout 'admin'
	def top
    @orders = Order.where(created_at: Time.zone.now.all_day)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
		@genres = Genre.where(is_status: true)
    @products = Product.where(is_status: true,genre_id: @genres).sample(3)
	end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.slim
- unless customer_signed_in?
  .row
    .col-xs-10.col-md-offset-1
      p
        |
          ようこそ、NaganoCakeへ！<br>
          このサイトは、ケーキ販売のECサイトになります。<br>
          会員でない方も商品の閲覧はできますが、<br>
          購入には
        = link_to '会員登録',new_customer_registration_path
        |
          が必要になります。

  .row
    .col-md-offset-1
      = render 'products/genre',genres: @genres

    .col-xs-9
      h2 今週のおすすめ
      = render 'products/products',products: @products

    .pull-right
      = link_to 'もっと見る>',products_path