config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers,only: [:show,:edit,:update]
  get '/customers/:id/leave' => "customers#leave"
  patch '/customers/:id/hide' => "customers#hide"
  resources :cart_items,only: [:index,:create,:destroy,:update]
  delete '/cart_items' => "cart_items#reset"
  get '/products/:genre_id/search' => "products#search"
  resources :products,only: [:index,:show]
  resources :shippings,only: [:new,:create,:edit,:update,:destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/complete' => "orders#complete"
  post '/orders/complete' => "orders#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders,only: [:new,:create,:index,:show]
  root to: 'home#top'
  namespace :admin do
  	get '/' => "home#top"
  	devise_for :administrators
  	resources :products,only: [:index,:new,:create,:show,:edit,:update]
  	resources :genres,only: [:index,:create,:edit,:update]
  	resources :customers,only: [:index,:show,:edit,:update]
  	resources :orders,only: [:index,:show,:update]
  	resources :order_details,only: [:update]
  end

  get 'admin/search' => "admin/search#search"
  get '/search' => "search#search"

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!
  before_action :cart_items_all,only: [:index,:destroy,:update,:reset]

  def index
  end

  def create
    @cart_item = current_customer.cart_items.new(product_id: params[:product_id],
                                                number: params[:cart_item][:number])
    if @cart_item.save
      redirect_to cart_items_path
    else
      @genres = Genre.where(is_status: true)
      @products = Product.find(params[:product_id])
      render 'products/show'
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.destroy
      # redirect_back(fallback_location: root_path)
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      # redirect_back(fallback_location: root_path)
    end
  end

  def reset
    if @cart_items.destroy_all
      redirect_to products_path, notice: "カートを空にしました。"
    else
      render :index ,notice: "カートを空にできませんでした。"
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:customer_id,:product_id,:number)
  end

  def cart_items_all
    @cart_items = CartItem.where(customer_id: current_customer.id)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def total_fee(resources) #複数のカートアイテムの配列を入れる
    fee = 0
    resources.each do |r|
      fee += (subtotal_fee(r))
    end
    return fee
  end

  def subtotal_fee(resource) #一種類のカートアイテムを入れる
    (tax_in_price(resource.product) * resource.number)
  end

  def total_number(resources)
    number = 0
    resources.each do |r|
      number += r.number
    end
    return number
  end
end

app/views/cart_items/_cart_item.html.erb
<table class="table table-bordered top-margin">
  <thead>
    <tr class="active">
      <div class="row">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th class="col-md-2">数量</th>
        <th>小計</th>
        <th class="col-md-1"></th>
      </div>
    </tr>
  </thead>
  <tbody>
    <% cart_items.each do |cart_item| %>
    <tr>
      <td><%= attachment_image_tag(cart_item.product, :image, :fill, 45,30, fallback: "no_image.jpg") %>  <%= cart_item.product.name %></td>
      <td><%= tax_in_price(cart_item.product) %></td>
      <td class="center form-group form-inline">
        <%= form_for cart_item,url: cart_item_path(cart_item), remote: true do |f| %>
          <%= f.number_field :number,class:"form-control",min: 1,max: 9 %>
          <%= f.submit '変更', class:"btn btn-primary btn-xs form-control" %>
        <% end %>
      </td>
      <td><%= subtotal_fee(cart_item).to_s(:delimited) %></td>
      <td class="text-center"><%= link_to '削除する',cart_item_path(cart_item), method: :delete, class:"btn btn-danger",remote: true %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/cart_items/destroy.js.erb
$("#cart-customer<%= current_customer.id %>").html("<%= j(render 'cart_item',cart_items: @cart_items) %>");
$("#cart-fee").html("<%= total_fee(@cart_items).to_s(:delimited) %>");

app/views/cart_items/index.html.erb
<% if @cart_items.blank? %>

<div class="center">
  <h3><%= kana_full_name(current_customer) %>さんのカートにはまだ何も追加されていません。</h3>
  <%= link_to '買い物を続ける',products_path,class:"btn btn-primary col-md-2 col-md-offset-5" %>
</div>

<% else %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">

    <div class="row">
      <h3>ショッピングカート
      <%= link_to 'カートを空にする',cart_items_path,method: :delete, class:"btn btn-danger pull-right" %></h3>
    </div>


          <div id="cart-customer<%= current_customer.id %>">
            <%= render 'cart_items/cart_item',cart_items: @cart_items %>
          </div>

    <div class="row">
      <%= link_to '買い物を続ける',root_path,class:"btn btn-primary col-md-2" %>
      <span class="pull-right col-md-4">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <div class="row">
                <th class="active col-md-6 total-fee">合計金額</th>
                <td class="total-fee" id="cart-fee"><%= total_fee(@cart_items).to_s(:delimited) %></td>
              </div>
            </tr>
          </tbody>
        </table>
      </span>
    </div>

    <div class="row center-block">
      <%= link_to '情報入力に進む',new_order_path,class:"btn btn-success btn-lg col-md-4 col-md-offset-4" %>
    </div>

  </div>
</div>

<% end %>

app/views/cart_items/update.js.erb
$("#cart-customer<%= current_customer.id %>").html("<%= j(render 'cart_item',cart_items: @cart_items) %>");
$("#cart-fee").html("<%= total_fee(@cart_items).to_s(:delimited) %>");