config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers,only: [:show,:edit,:update]
  get '/customers/:id/leave' => "customers#leave"
  patch '/customers/:id/hide' => "customers#hide"
  resources :cart_items,only: [:index,:create,:destroy,:update]
  delete '/cart_items' => "cart_items#reset"
  get '/products/:genre_id/search' => "products#search"
  resources :products,only: [:index,:show]
  resources :shippings,only: [:new,:create,:edit,:update,:destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/complete' => "orders#complete"
  post '/orders/complete' => "orders#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders,only: [:new,:create,:index,:show]
  root to: 'home#top'
  namespace :admin do
  	get '/' => "home#top"
  	devise_for :administrators
  	resources :products,only: [:index,:new,:create,:show,:edit,:update]
  	resources :genres,only: [:index,:create,:edit,:update]
  	resources :customers,only: [:index,:show,:edit,:update]
  	resources :orders,only: [:index,:show,:update]
  	resources :order_details,only: [:update]
  end

  get 'admin/search' => "admin/search#search"
  get '/search' => "search#search"

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_details
  has_many :cart_items, dependent: :destroy
  enum is_status: { 売切れ: false, 販売中: true }
  validates :name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :price, presence: true
  attachment :image

  def self.search(search)
    return Product.all unless search
    Product.where(["name LIKE ? OR description LIKE ?", "%#{search}%","%#{search}%"])
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	before_action :authenticate_admin_administrator!
	layout 'admin'
	def new
		@product = Product.new
	end

	def create
	    @product = Product.new(product_params)
	   if   @product.save
	   	    flash[:success] = "商品情報が登録されました。"
	        redirect_to admin_product_path(@product)
	   else
	        render 'new'
	   end
	end

	def index
	    @products = Product.page(params[:page])
	    @product = Product.new
	    @genres = Genre.all
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
	   if  @product.update(product_params)
	   	   flash[:success] = "商品情報が更新されました。"
	       redirect_to admin_product_path
	   else
	       render 'edit'
	   end
	end

	def show
		@product = Product.find(params[:id])
	end

	private
    def product_params
        params.require(:product).permit(:name, :description, :image, :price, :is_status, :genre_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :valid_genre

    def index
        @products = Product.where(is_status: true,genre_id: @genres)
	end

	def show
        @product = Product.find(params[:id])
      unless @product.is_status == '販売中' && @product.genre.is_status == '有効'
        redirect_to products_path
      end
        @cart_item = CartItem.new
	end

    def search
        @genre = Genre.find(params[:genre_id])
        if @genre.is_status == '有効'
            @products = Product.where(genre_id: params[:genre_id])
        else
            redirect_to products_path
        end
    end

    def price
    end

    private

    def valid_genre
        @genres = Genre.where(is_status: true)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def tax_in_price(product)
    (product.price*1.1).round
  end
end

app/views/admin/products/edit.html.erb
<div class="row">
      <div class="col-xs-4">
	<h1>商品編集</h1>
	     <%= form_for @product, url: admin_product_path(@product) do |f| %>
	            <%= f.attachment_field :image %>
	     　　<h4>商品名</h4>
             　　　<%= f.text_field :name %>
             <h4>商品説明</h4>
             　　　<%= f.text_area :description %>
             <h4>ジャンル</h4>
                  <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: true %>
             <h4>税抜価格</h4>
                  <%= f.text_field :price %>円
             <h4>販売ステータス</h4>
             　　　 <%= f.select :is_status,{ 販売中:"販売中", 売切れ:"売切れ"} %>     
       　<%= f.submit '変更を保存',class: 'btn btn-primary' %> 
      </div>   
         <% end %>
</div>             

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
    	<h2 class="col-md-6">商品一覧</h2>
      <div class="productnew col-md-3">
      　　<%= link_to "+", new_admin_product_path, class: 'btn btn-default btn-lg pull-right' %>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
       　　<th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
    	 <% @products.each do |product| %>
    	 <tr>
    	 	<td><%= product.id %></td>
    	 	<td><%= link_to product.name,admin_product_path(product.id) %></td>
    	 	<td><%= product.price %></td>
    	 	<td><%= product.genre.name %></td>
    	 	<td><%= product.is_status %></td>
    	 </tr>
    	 <% end %>
       <%= paginate @products %>
      </tbody>
    </table>

  </div>
</div>

app/views/admin/products/new.html.erb
<div class="row">
  <h2>商品新規登録</h2>
     <div class="col-xs-4">   
    <%= form_for @product, url:  admin_products_path(@product) do |f| %>
         <%= f.attachment_field :image %>
         　　<h4>商品名</h4>
                 <%= f.text_field :name %>
            <h4>商品説明</h4>
                  <%= f.text_area :description %>
            <h4>ジャンル</h4>
                  <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: true %>
            <h4>税抜価格</h4>
                  <%= f.text_field :price %>円
            <h4>販売ステータス</h4>
                  <%= f.select :is_status,{ 販売中:"販売中", 売切れ:"売切れ"} %>
    <%= f.submit '新規登録',class: 'btn btn-primary' %>  
    <% end %> 
      </div>
</div>

app/views/admin/products/show.html.erb
  <p class="notice">
       <%= flash[:success] %>
  </p>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="col-xs-4">
        <h2>商品詳細</h2>
        <%= attachment_image_tag @product, :image, format: 'jpeg', size: "300x200" %>
      </div>

      <div class="col-xs-4">
        <h4><b>商品名</b></h4>
            <%= @product.name %>
        <h4><b>商品説明</b></h4>
            <%= @product.description %>
        <h4><b>ジャンル</b></h4>
            <%= @product.genre.name %>
        <h4><b>税込価格（税抜価格）</b></h4>
            <%= tax_in_price(@product) %>
            (<%= @product.price %>) 円

        <h4><b>販売ステータス</b></h4>
            <%= @product.is_status %>
      </div>

      <div class="col-xs-4">
        <div class="productshow">
          <%= link_to '編集する', edit_admin_product_path(@product), class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>
</div>