config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers,only: [:show,:edit,:update]
  get '/customers/:id/leave' => "customers#leave"
  patch '/customers/:id/hide' => "customers#hide"
  resources :cart_items,only: [:index,:create,:destroy,:update]
  delete '/cart_items' => "cart_items#reset"
  get '/products/:genre_id/search' => "products#search"
  resources :products,only: [:index,:show]
  resources :shippings,only: [:new,:create,:edit,:update,:destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/complete' => "orders#complete"
  post '/orders/complete' => "orders#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders,only: [:new,:create,:index,:show]
  root to: 'home#top'
  namespace :admin do
  	get '/' => "home#top"
  	devise_for :administrators
  	resources :products,only: [:index,:new,:create,:show,:edit,:update]
  	resources :genres,only: [:index,:create,:edit,:update]
  	resources :customers,only: [:index,:show,:edit,:update]
  	resources :orders,only: [:index,:show,:update]
  	resources :order_details,only: [:update]
  end

  get 'admin/search' => "admin/search#search"
  get '/search' => "search#search"

end

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController
  before_action :authenticate_admin_administrator!
  layout 'admin'
  def search
    if !Customer.search(params[:search]).blank?
      # カスタマーで検索がヒットした場合
      @customers = Customer.search(params[:search])
    elsif !Product.search(params[:search]).blank?
      # 商品で検索がヒットした場合
      @products = Product.search(params[:search])
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @genres = Genre.where(is_status: true)
    @products = Product.search(params[:search]).where(is_status: true,genre_id: @genres)
  end
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/search/search.html.erb
<% if @customers %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table class="table">
        <caption>会員検索結果<small>(<%= @customers.count %>件)</small></caption>
        <thead>
          <tr class="active">
            <th>ID</th>
            <th>会員名</th>
            <th>フリガナ</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |c| %>
              <tr>
                <td><%= c.id %></td>
                <td><%= link_to kanji_full_name(c),admin_customer_path(c) %></td>
                <td><%= kana_full_name(c) %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<% elsif @products %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table class="table">
        <caption>商品検索結果<small>(<%= @products.count %>件)</small></caption>
        <thead>
          <tr class="active">
            <th>ID</th>
            <th>商品名</th>
            <th>価格</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |p| %>
              <tr>
                <td><%= p.id %></td>
                <td><%= link_to p.name,admin_product_path(p) %></td>
                <td><%= p.price %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<% else %>

  <h1 class="center">検索結果はありません</h1>

<% end %>